config/routes.rb
Rails.application.routes.draw do
  resources :workflows, only: [:index, :new, :show]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/workflows_controller.rb
class WorkflowsController < ApplicationController
  before_action :load_embed_workflow_jwt

  def index
  end

  def show
  end

  def new
  end

  private
    def load_embed_workflow_jwt
      return @embed_workflow_jwt if defined?(@embed_workflow_jwt)

      current_time = Time.now.to_i
      exp          = current_time + 3600
      payload      = { sub: ENV["EMBED_WORKFLOW_USER_KEY"], exp: exp, iat: current_time }

      @embed_workflow_jwt = JWT.encode(payload, ENV["EMBED_WORKFLOW_SECRET_KEY"], "HS256")
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EmbedWorkflowRailsSample</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/workflows/index.html.erb
<%= render "embed_workflow_scripts" %>

<%= link_to "New workflow", new_workflow_path %>

<h1>Workflows</h1>

<div>
  <div class="EWF__workflows_table" data-on-click="openWorkflow"></div>
</div>

<script type="text/javascript">
  var loadEmbed = function () {
    EWF.load("<%= ENV['EMBED_WORKFLOW_PUBLISHABLE_KEY'] %>", { jwt: "<%= @embed_workflow_jwt %>" });
  }

  loadEmbed();

  var openWorkflow = function (hashid) {
    window.location = "/workflows/" + hashid;
  }
</script>

app/views/workflows/new.html.erb
<%= render "embed_workflow_scripts" %>

<div>
  <%= link_to "Back to workflows", workflows_path %>
</div>

<h1>New workflow</h1>

<div>
  <div class="EWF__workflow_form" data-after-success="openWorkflow"></div>
</div>

<script type="text/javascript">
  var loadEmbed = function () {
    EWF.load("<%= ENV['EMBED_WORKFLOW_PUBLISHABLE_KEY'] %>", { jwt: "<%= @embed_workflow_jwt %>" });
  }

  loadEmbed();

  var openWorkflow = function (workflow) {
    window.location = "/workflows/" + workflow.hashid;
  }
</script>

app/views/workflows/show.html.erb
<%= render "embed_workflow_scripts" %>

<%= link_to "Back to Workflows", workflows_path %>

<div class="EWF__workflow_settings" data-hashid="<%= params[:id] %>"></div>

<script type="text/javascript">
  var loadEmbed = function () {
    EWF.load("<%= ENV['EMBED_WORKFLOW_PUBLISHABLE_KEY'] %>", { jwt: "<%= @embed_workflow_jwt %>" });
  }

  loadEmbed();
</script>